### ISSUE TITLE
[SUGGESTION] Add Export to Not Allow the use of the Menu

### ISSUE THREAD

**Issue by JohnnyS** [baguscodestudio/bcs_radialmenu#1]
Useful for not using the menu while you are dead for example. I have my phone on that and people are able to use the phone off the menu while dead

**Comment by baguscodestudio** [comment]
Instead of disabling it, i will make another option of selections which only shows when they are dead. This can be triggered with export like you said.

**Comment by JohnnyS** [comment]
Ah thats nice as well! People could put like a panic button for example

**Comment by baguscodestudio** [comment]
![image](https://user-images.githubusercontent.com/60974759/159837624-af88a6a5-4b76-4bd1-a541-1d8e424b1ec6.png)
I have added 2 new export functions `setDead` and `disable`
