### ISSUE TITLE
back to previous menu

### ISSUE THREAD

**Issue by BlacknGoldy** [baguscodestudio/bcs_radialmenu#2]
Hi,
first of all thank you for your sharing and i love the work. 👍 🥇 

i have one issue, cant call it issue but when you are going inside the menu and choosing for example work and etc. there is no way back only way is closing and start again?
if not can be added instead of closing and start again have a back option and when you are in main menu can close (for fast closing can use key ESC) :)

**Comment by baguscodestudio** [comment]
Thanks for the suggestions, I will be updating it in the next update with another changes.
